package servent.message;

public enum MessageType {
	NEW_NODE, WELCOME, SORRY, UPDATE, TELL_GET, HAIL, POISON, READY, STATUS_ASK, STATUS_REPLY, STATUS_SPECIFIC,
    RESULT_ASK, RESULT_REPLY, RESULT_SPECIFIC, NUMS, IDLE, QUIT_JOB, NEIGHBOUR_QUIT
}
